### ISSUE TITLE
python main.py errors.

### ISSUE THREAD

**Issue by jiapei100** [fomorians/distracted-drivers-keras#2]
Two issues:

1) Why it is defaulty select Theano as the backend? How can I modify main.py to select TensorFlow as the backend?

2) python main.py gives me the following error message

```
.../distracted-drivers-keras$ python main.py 
Using Theano backend.
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python3.5/dist-packages/Keras-1.0.1-py3.5.egg/keras/models.py", line 5, in <module>
    from . import backend as K
  File "/usr/local/lib/python3.5/dist-packages/Keras-1.0.1-py3.5.egg/keras/backend/__init__.py", line 51, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python3.5/dist-packages/Keras-1.0.1-py3.5.egg/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python3.5/dist-packages/Theano-0.8.0-py3.5.egg/theano/__init__.py", line 64, in <module>
    from theano.compile import (
  File "/usr/local/lib/python3.5/dist-packages/Theano-0.8.0-py3.5.egg/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/usr/local/lib/python3.5/dist-packages/Theano-0.8.0-py3.5.egg/theano/compile/function_module.py", line 22, in <module>
    import theano.compile.mode
  File "/usr/local/lib/python3.5/dist-packages/Theano-0.8.0-py3.5.egg/theano/compile/mode.py", line 77, in <module>
    OPT_NONE = gof.Query(include=[], exclude=exclude)
  File "/usr/local/lib/python3.5/dist-packages/Theano-0.8.0-py3.5.egg/theano/gof/optdb.py", line 173, in __init__
    self.include = OrderedSet(include)
  File "/usr/local/lib/python3.5/dist-packages/Theano-0.8.0-py3.5.egg/theano/misc/ordered_set.py", line 91, in __init__
    root.prev = root.__next__ = weakref.ref(root)
AttributeError: 'Link' object has no attribute '__next__'
```

**Comment by gauss256** [comment]
You need to configure Keras to use TensorFlow as the backend.

http://keras.io/backend/

**Comment by jiapei100** [comment]
Yes, Great gauss256. Thank you very much....

1) However, even if I stick to the backend theano, I should be able to train a model, instead of getting the above error messages????? Because I do have both tensorflow and theano installed....

2) Can you please also help to check this issue for me ?
https://github.com/fomorians/distracted-drivers-tf/issues/3

Thanks ....
